workflows:
  android-build:
    name: Android Debug Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      vars:
        JAVA_VERSION: "17"
    scripts:
      - name: Set up Java
        script: |
          export JAVA_HOME=$JAVA_HOME_17_X64
      - name: Give Gradlew Execute Permissions
        script: chmod +x ./gradlew
      - name: Build APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
